export const FETCH_ALL_PRODUCT = 'FETCH_ALL_PRODUCT'
export const FETCH_ALL_PRODUCT_SUCCESS = 'FETCH_ALL_PRODUCT_SUCCESS'
export const FETCH_ALL_PRODUCT_FAILED = 'FETCH_ALL_PRODUCT_FAILED'

export const FILTER_PRODUCT = 'FILTER_PRODUCT'
export const FILTER_PRODUCT_SUCCESS = 'FILTER_PRODUCT_SUCCESS'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED'

export const SET_PRODUCT_EDITING = 'SET_PRODUCT_EDITING'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED'

export const SORT_PRODUCT = 'SORT_PRODUCT'
export const SORT_PRODUCT_SUCCESS = 'SORT_PRODUCT_SUCCESS'